version: '3.9'

services:
  frontend:
    build:
      context: ./frontend # Carpeta del submódulo frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Puerto donde se ejecuta el frontend
    volumes:
      - ./frontend/build:/usr/share/nginx/html  # Si es necesario, ajusta el path para nginx
    depends_on:
      - backend

  backend:
    build:
      context: ./backend # Carpeta del submódulo backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001" # Puerto donde se ejecuta el backend
    environment:
      - PORT=8001
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=12345678
      - DB_NAME=rrhh_control
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: rrhh_control
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
